tas_single_node_base_hostname: myrhtas
tas_single_node_cockpit:
  enabled: false
tas_single_node_registry_username: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_USERNAME') }}"
tas_single_node_registry_password: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_PASSWORD') }}"
tas_single_node_podman_volume_create_extra_args:
  redis_backfill_storage: "--opt type=none --opt device=/home/root/volumes/redis-backfill-storage --opt o=bind"
  rekor_server: "--opt type=none --opt device=/home/root/volumes/rekor-server --opt o=bind"
  tuf_repository: "--opt type=none --opt device=/home/root/volumes/tuf-repository --opt o=bind"
  tuf_signing_keys: "--opt type=none --opt device=/home/root/volumes/tuf-signing-keys --opt o=bind"
tas_single_node_trillian:
  database_deploy: false
  mysql:
    user: mysql
    root_password: rootpassword
    password: password
    database: trillian
    host: "{{ ansible_default_ipv4.address }}"
    port: 3306
  trusted_ca: "{{ ca_cert_content.content | b64decode }}"
tas_single_node_rekor_redis:
  database_deploy: false
  redis:
    host: "{{ ansible_default_ipv4.address }}"
    port: 6379
    password: password
tas_single_node_tsa:
  ca_passphrase: rhtas
  signer_type: file
  ntp_config: "{{ lookup('file', molecule_scenario_directory + '/test_creds/ntpsync.yaml') }}"
  signer_private_key: "{{ lookup('file', molecule_scenario_directory + '/test_creds/private-key.pem') }}"
  certificate_chain: "{{ lookup('file', molecule_scenario_directory + '/test_creds/cert-chain.pem') }}"
  trusted_ca: ""

tas_single_node_ctlog:
  sharding_config:
    - config:
      treeid:
      prefix: "rhtasansible"
      root_pem_file: "/ctfe-keys/fulcio-0"
      password: "password"
      private_key: "private-ctlog-key1"
  private_keys:
    - id: "private-ctlog-key1"
      key: |
        {{ lookup('file', molecule_scenario_directory + '/test_creds/ctlog/ctlog0.key') }}
  public_keys:
    - id: "public-ctlog-key1"
      key: |
        {{ lookup('file', molecule_scenario_directory + '/test_creds/ctlog/ctlog0.pub') }}

tas_single_node_fulcio:
  trusted_ca: "{{ lookup('file', '../common/dex/tls.crt') }}"
  private_key: |
    {{ lookup('file', molecule_scenario_directory + '/test_creds/fulcio.key') }}
  root_ca: |
    {{ lookup('file', molecule_scenario_directory + '/test_creds/fulcio.pem') }}
  ca_passphrase: password
  fulcio_config:
    meta_issuers:
      - issuer_pattern: "https://dex-*:5556/dex"
        client_id: trusted-artifact-signer
        type: email

tas_single_node_rekor:
  ca_passphrase: password
  public_key_retries: 5
  active_tree_id: 0
  public_key_delay: 10
  active_signer_type: file
  active_signer_id: rekor-private-key1
  private_keys: 
    - id: "rekor-private-key1"
      key: |
        {{ lookup('file', molecule_scenario_directory + '/test_creds/rekor/rekortest.key') }}
  public_keys: 
    - id: "rekor-public-key1"
      key: |
        {{ lookup('file', molecule_scenario_directory + '/test_creds/rekor/rekortest.pub') }}
