tas_single_node_oidc_issuers:
  - issuer: "http://dex-idp:5556/dex"
    url: "http://dex-idp:5556/dex"
    client_id: example-app
    type: email
tas_single_node_base_hostname: myrhtas
tas_single_node_cockpit:
  enabled: false
tas_single_node_registry_username: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_USERNAME') }}"
tas_single_node_registry_password: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_PASSWORD') }}"
tas_single_node_trillian:
  database_deploy: false
  mysql:
    user: mysql
    root_password: rootpassword
    password: password
    database: trillian
    host: "{{ ansible_default_ipv4.address }}"
    port: 3306
  trusted_ca: "{{ ca_cert_content.content | b64decode }}"
tas_single_node_rekor_redis:
  database_deploy: false
  redis:
    host: "{{ ansible_default_ipv4.address }}"
    port: 6379
    password: password
tas_single_node_tsa:
  signer_type: file
  signer_passphrase: rhtas
  ntp_config: "{{ lookup('file', molecule_scenario_directory + '/test_creds/ntpsync.yaml') }}"
  signer_private_key: "{{ lookup('file', molecule_scenario_directory + '/test_creds/private-key.pem') }}"
  certificate_chain: "{{ lookup('file', molecule_scenario_directory + '/test_creds/cert-chain.pem') }}"
  trusted_ca: ""
tas_single_node_custom_ctlog_public_key_names: []
tas_single_node_custom_ctlog_private_key_names: []

tas_single_node_ctlog:
  sharded_config:
    - config:
      treeid:
      prefix: "rhtasansible"
      root_pem_file: "/ctfe-keys/fulcio-0"
      password: "password"
      private_key: "private-0"
  private_keys:
    - |
      {{ lookup('file', molecule_scenario_directory + '/test_creds/ctlog0.key') }}
  public_keys:
    - |
      {{ lookup('file', molecule_scenario_directory + '/test_creds/ctlog0.pub') }}


