apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillian-logsigner
  namespace: trillian-system
  labels:
    app.kubernetes.io/component: trillian-logsigner
    app.kubernetes.io/instance: scaffold
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trillian
    helm.sh/chart: trillian-0.1.16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trillian-logsigner
  template:
    metadata:
      labels:
        app: trillian-logsigner
        app.kubernetes.io/component: trillian-logsigner
        app.kubernetes.io/instance: scaffold
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: trillian
        helm.sh/chart: trillian-0.1.16
    spec:
      initContainers:
        - name: wait-for-trillian-db
          image: "{{ tas_single_node_netcat_image}}"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until nc -z -w 10 trillian-mysql-pod 3306; do echo waiting for trillian-mysql-pod; sleep 5; done;"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name: trillian-trillian-logsigner
          image: "{{ tas_single_node_trillian_logsigner_image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8191
              protocol: TCP
          args:
            - --storage_system=mysql
            - --quota_system=mysql
            - --mysql_uri={{ tas_single_node_trillian.mysql.user }}:{{ tas_single_node_trillian.mysql.password }}@tcp({{ tas_single_node_trillian.mysql.host }}:{{ tas_single_node_trillian.mysql.port }})/{{ tas_single_node_trillian.mysql.database }}
            - --rpc_endpoint=0.0.0.0:8091
            - --http_endpoint=0.0.0.0:8090
            - --force_master=true
            - --alsologtostderr
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-user
                  name: trillian-mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: trillian-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: mysql-database
                  name: trillian-mysql
            - name: MYSQL_HOSTNAME
              value: "{{ tas_single_node_trillian.mysql.host }}"
            - name: MYSQL_PORT
              value: "{{ tas_single_node_trillian.mysql.port | quote }})"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: minikube
      nodeSelector:
        kubernetes.io/arch: arm64
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: trillian-logsigner
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
