---
- name: Prepare
  hosts: worker_group
  gather_facts: false
  become: true
  vars:
    users:
      - user: testingUser
        password: password123
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Configure Dex OIDC instance
      ansible.builtin.include_tasks: ../common/dex-setup.yaml
