- name: Verify
  hosts: worker_group
  gather_facts: true
  become: true
  vars:
    test_dir_path: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../../vm-testing/test"
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Include create common tasks
      ansible.builtin.include_tasks:
        file: ../common/verify_common.yml
