---
namespace: redhat
name: artifact_signer
version: 1.0.0

readme: README.md
authors:
  - Andrew Block <ablock@redhat.com>
  - Firas Ghanmi <fghanmi@redhat.com>
  - Nina Olear <nolear@redhat.com>
  - Ryan Cook <rcook@redhat.com>
  - Slavek Kabrda <bkabrda@redhat.com>
  - Tommy Dalton <tdalton@redhat.com>
  - Aleksy Siek <asiek@redhat.com>
description: Install and configure RHTAS, a downstream redistribution of the Sigstore project.
license_file: Apache-2.0
tags: [sigstore, tas, rhtas, security, cosign]
# NOTE: when updating, also update dependencies in requirements.yml
dependencies:
  containers.podman: ">=1.15.0"
repository: https://github.com/securesign/artifact-signer-ansible/
documentation: http://TODO.com
homepage: https://github.com/securesign/artifact-signer-ansible#rhtas-ansible-collection
issues: https://github.com/securesign/artifact-signer-ansible/issues

build_ignore:
  - .ansible-lint
  - .github
  - .gitignore
  - .vscode
  - ansible-navigator.log
  - Makefile
  - molecule
  - requirements-testing.txt
  - roles/tas_single_node/README.j2
  - vm-testing
