---
namespace: redhat
name: artifact_signer
version: 1.3.0+dev.1

readme: README.md
authors:
  - Andrew Block <ablock@redhat.com>
  - Firas Ghanmi <fghanmi@redhat.com>
  - Nina Olear <nolear@redhat.com>
  - Ryan Cook <rcook@redhat.com>
  - Slavek Kabrda <bkabrda@redhat.com>
  - Tommy Dalton <tdalton@redhat.com>
  - Aleksy Siek <asiek@redhat.com>
description: Install and configure RHTAS, a downstream redistribution of the Sigstore project.
license_file: LICENSE
tags: [sigstore, tas, rhtas, security, cosign]
# NOTE: when updating, also update dependencies in requirements.yml
dependencies:
  ansible.posix: ">=1.5.4"
repository: https://github.com/securesign/artifact-signer-ansible/
documentation: https://docs.redhat.com/en/documentation/red_hat_trusted_artifact_signer
homepage: https://github.com/securesign/artifact-signer-ansible#rhtas-ansible-collection
issues: https://github.com/securesign/artifact-signer-ansible/issues

build_ignore:
  - .ansible-lint
  - .github
  - .gitignore
  - .vscode
  - ansible-navigator.log
  - Makefile
  - molecule
  - testing-requirements.txt
  - roles/tas_single_node/README.j2
  - vm-testing
