---
namespace: redhat
name: artifact_signer
version: 1.0.0

readme: README.md
authors:
  - Red Hat
  - TODO
description: TODO
license_file: Apache-2.0
tags: [sigstore, tas, rhtas, security, cosign]
# NOTE: when updating, also update dependencies in requirements.yml
dependencies: {}
repository: https://github.com/securesign/artifact-signer-ansible/
documentation: http://TODO.com
homepage: https://TODO.com
issues: https://github.com/securesign/artifact-signer-ansible/issues

build_ignore: [.ansible-lint, .github, .gitignore, .vscode, requirements-testing.txt, vm-testing]
