tas_single_node_base_hostname: myrhtas
tas_single_node_cockpit:
  enabled: false
aap_setup_prep_inv_secrets:
  all:
    registry_username: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_USERNAME') }}"
    registry_password: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_PASSWORD') }}"
