tas_single_node_fulcio:
  trusted_ca: "{{ lookup('file', '../common/dex/tls.crt') }}"
  fulcio_config:
    oidc_issuers:
      - issuer: "https://dex-idp:5556/dex"
        url: "https://dex-idp:5556/dex"
        client_id: trusted-artifact-signer
        type: email
      - issuer: "sigstore"
        url: "https://oauth2.sigstore.dev/auth"
        client_id: sigstore
        type: email
tas_single_node_base_hostname: myrhtas
tas_single_node_cockpit:
  enabled: false
tas_single_node_registry_username: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_USERNAME') }}"
tas_single_node_registry_password: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_PASSWORD') }}"
tas_single_node_trillian:
  database_deploy: false
  db:
    provider: postgresql
    user: postgres
    password: password
    database: trillian
    host: "{{ ansible_default_ipv4.address }}"
    port: 5432
