---
- name: DestroyTAS
  hosts: molecule
  gather_facts: true
  become: true
  vars:
    users:
      - user: testingUser
        password: password123
  vars_files:
    - vars/podman.yml
    - vars/vars.yml
  tasks:
    - name: Stop all containers
      ansible.builtin.shell: podman container stop -a -t 1
      become: true

    - name: Delete all containers
      ansible.builtin.shell: podman container rm -f -a
      become: true

    - name: Delete all container volumes
      ansible.builtin.shell: podman volume rm -f -a
      become: true

    - name: Configure Dex OIDC instance
      ansible.builtin.include_tasks: ../common/dex-setup.yaml

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /etc/rhtas
        state: absent
        mode: "0777"
