s#registry.redhat.io/rhtas/trillian-logsigner-rhel9#quay.io/securesign/trillian-logsigner#
s#registry.redhat.io/rhtas/trillian-logserver-rhel9#quay.io/securesign/trillian-logserver#
s#registry.redhat.io/rhtas/trillian-database-rhel9#quay.io/securesign/trillian-database#
s#registry.redhat.io/rhtas/fulcio-rhel9#quay.io/securesign/fulcio-server#
s#registry.redhat.io/rhtas/trillian-redis-rhel9#quay.io/securesign/trillian-redis#
s#registry.redhat.io/rhtas/rekor-server-rhel9#quay.io/securesign/rekor-server#
s#registry.redhat.io/rhtas/rekor-search-ui-rhel9#quay.io/securesign/rekor-search-ui#
s#registry.redhat.io/rhtas/rekor-backfill-redis-rhel9#quay.io/securesign/trillian-redis#
s#registry.redhat.io/rhtas/tuf-server-rhel9#quay.io/securesign/scaffold-tuf-server#
s#registry.redhat.io/rhtas/certificate-transparency-rhel9#quay.io/securesign/certificate-transparency-go#
s#registry.redhat.io/rhtas/client-server-cg-rhel9#quay.io/securesign/cli-client-server-cg#
s#registry.redhat.io/rhtas/client-server-re-rhel9#quay.io/securesign/client-server-re#
s#registry.redhat.io/rhtas/segment-reporting-rhel9#quay.io/securesign/segment-backup-job#
