issuer: http://dex-idp:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
- id: example-app
  redirectURIs:
  - 'http://dex-idp:5556/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

connectors:
- type: mockCallback
  id: mock
  name: Example

enablePasswordDB: true

staticPasswords:
- email: "admin@example.com"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
- email: "jdoe@redhat.com"
  hash: "$2y$10$DajldwSiGeSKe.2FsuTkueyhtvjdhkgBpisLrY.1Bdr4KlYeefn9O" # secure
  username: "jdoe"
  userID: "123456"

oauth2:
  responseTypes: ["code"]
  alwaysShowLoginScreen: true
  skipApprovalScreen: true
  passwordConnection: mock

expiry:
  signingKeys: "24h"
  idTokens: "1m"
  authRequests: "24h"
