---
- name: Run Manual Backup and Exit
  when: tas_single_node_data_protection.backup.force_run and
        not tas_single_node_data_protection.restore.enabled
  block:
    - name: Run Backup Oneshot Job
      ansible.builtin.systemd:
        name: tas_backup.service
        state: started

    - name: Exit after Backup
      ansible.builtin.meta: end_host

- name: Run TAS System Restore
  ansible.builtin.include_tasks: podman/restore.yml
  when: tas_single_node_data_protection.restore.enabled and
        not tas_single_node_data_protection.backup.force_run

- name: Check configuration correctness
  ansible.builtin.include_tasks: configuration_check.yml

- name: Check OS Support
  ansible.builtin.include_tasks: os_support.yml

- name: Install Operating System Components
  ansible.builtin.include_tasks: os.yml
  when: not tas_single_node_skip_os_install

- name: Create cockpit-user
  ansible.builtin.user:
    name: "{{ tas_single_node_cockpit.user.username }}"
    shell: /bin/bash
    group: wheel
    password: "{{ tas_single_node_cockpit.user.password | password_hash('sha512') }}"
    create_home: true
  when:
    - tas_single_node_cockpit.enabled | bool
    - tas_single_node_cockpit.user.create | bool

- name: Install Cockpit
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.cockpit
  vars:
    cockpit_packages:
      - cockpit-storaged
      - cockpit-podman
      - cockpit
    cockpit_manage_firewall: true
  when: tas_single_node_cockpit.enabled | bool

- name: Create Certificates
  ansible.builtin.include_tasks: certificates.yml

- name: Execute Podman Actions
  ansible.builtin.include_tasks: podman.yml
