---
- name: Install System Packages dependencies
  ansible.builtin.package:
    name: "{{ tas_single_node_system_packages }}"

- name: Install Cockpit
  ansible.builtin.include_role:
    name: cockpit
  vars:
    cockpit_packages: "{{ tas_single_node_cockpit.cockpit_packages }}"
    cockpit_manage_firewall: "{{ tas_single_node_cockpit.cockpit_manage_firewall }}"
  when: tas_single_node_cockpit.enabled | bool

- name: Configure /etc/hosts DNS block
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('ansible.builtin.template', 'configs/etc-hosts.j2') }}"
    state: present
    create: true
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED INGRESS BLOCK"
  when: tas_single_node_setup_host_dns | bool
