---
- name: Install System Packages dependencies
  # We use noqa here, because having all the packages upgrade to the latest version when
  # available is actually what we want. We need to prevent locking ourselves at old
  # version with potential CVEs (at the same time we must upgrade to at least RHEL 9.4
  # package releases to ensure we can actually work).
  ansible.builtin.package: # noqa: package-latest
    name: "{{ tas_single_node_system_packages }}"
    state: latest
    enable_plugin: # respect user's version locked packages, if any
      - versionlock

- name: Configure /etc/hosts DNS block
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('ansible.builtin.template', 'configs/etc-hosts.j2') }}"
    state: present
    create: true
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED INGRESS BLOCK"
  when: tas_single_node_setup_host_dns | bool

- name: Construct Podman registry configuration blocks
  ansible.builtin.set_fact:
    podman_registry_block: |
      {% for item in tas_single_node_podman.registry %}
      [[registry]]
      location = "{{ item.location }}"
      [[registry.mirror]]
      location = "{{ item.mirror }}"
      {% endfor %}
  when: tas_single_node_podman.registry is defined

- name: Configure Podman registry mirror
  ansible.builtin.blockinfile:
    path: /etc/containers/registries.conf
    marker: "# {mark} ANSIBLE MANAGED REGISTRY BLOCK"
    block: "{{ podman_registry_block }}"
  when: tas_single_node_podman.registry is defined

- name: Replace /etc/containers/policy.json
  ansible.builtin.copy:
    content: "{{ tas_single_node_podman.policy }}"
    dest: /etc/containers/policy.json
    owner: root
    group: root
    mode: '0644'
  when: tas_single_node_podman.policy is defined
