---
- name: Confirmed required parameters provided
  ansible.builtin.assert:
    that:
      - tas_single_node_base_hostname is defined
      - tas_single_node_base_hostname | trim | length > 0
    msg: "'tas_single_node_base_hostname' must be specified"

- name: Get RHTAS network details
  containers.podman.podman_network:
    name: "{{ tas_single_node_podman_network }}"
  register: tas_podman_network_results

- name: Set DNS Resolver
  ansible.builtin.set_fact:
    dns_resolver: "{{ tas_podman_network_results.network.subnets[0].gateway }}"

- name: Slurp ingress Certificates
  ansible.builtin.slurp:
    src: "{{ item }}"
  loop:
    - "{{ tas_single_node_remote_ca }}"
    - "{{ tas_single_node_certs_dir }}/ingress-rekor.pem"
    - "{{ tas_single_node_certs_dir }}/ingress-rekor.key"
    - "{{ tas_single_node_certs_dir }}/ingress-tuf.pem"
    - "{{ tas_single_node_certs_dir }}/ingress-tuf.key"
    - "{{ tas_single_node_certs_dir }}/ingress-fulcio.pem"
    - "{{ tas_single_node_certs_dir }}/ingress-fulcio.key"
    - "{{ tas_single_node_certs_dir }}/ingress-tsa.pem"
    - "{{ tas_single_node_certs_dir }}/ingress-tsa.key"
  register: remote_ingress_certificates

- name: Base64 encode the rekor ingress
  ansible.builtin.set_fact:
    rekor_ingress_base64: >-
      {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-rekor.pem') | list | first).content
      | b64decode + (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_remote_ca) | list | first).content
      | b64decode }}

- name: Base64 encode the tuf ingress
  ansible.builtin.set_fact:
    tuf_ingress_base64: >-
      {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-tuf.pem') | list | first).content
      | b64decode + (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_remote_ca) | list | first).content
      | b64decode }}

- name: Base 64 encode the fulcio ingress
  ansible.builtin.set_fact:
    fulcio_ingress_base64: >-
      {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-fulcio.pem') | list | first).content
      | b64decode + (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_remote_ca) | list | first).content
      | b64decode }}

- name: Base 64 encode the tsa ingress
  ansible.builtin.set_fact:
    tsa_ingress_base64: >-
      {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-tsa.pem') | list | first).content
      | b64decode + (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_remote_ca) | list | first).content
      | b64decode }}

- name: Create nginx certs Secret
  ansible.builtin.copy:
    content: "{{ secret_content | to_nice_yaml(indent=2) }}"
    dest: "{{ tas_single_node_nginx_certs_config }}"
    mode: "0600"
  vars:
    secret_content:
      kind: Secret
      apiVersion: v1
      metadata:
        name: nginx-certs
        namespace: nginx-system
      data:
        ingress-rekor.pem: |
          {{ rekor_ingress_base64 | b64encode }}
        ingress-tuf.pem: |
          {{ tuf_ingress_base64 | b64encode }}
        ingress-fulcio.pem: |
          {{ fulcio_ingress_base64 | b64encode }}
        ingress-tsa.pem: |
          {{ tsa_ingress_base64 | b64encode }}
        ingress-rekor.key: |
          {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-rekor.key') | list | first).content }}
        ingress-tuf.key: |
          {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-tuf.key') | list | first).content }}
        ingress-fulcio.key: >-
          {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir
          + '/ingress-fulcio.key') | list | first).content }}
        ingress-tsa.key: |
          {{ (remote_ingress_certificates.results | selectattr('source', 'equalto', tas_single_node_certs_dir + '/ingress-tsa.key') | list | first).content }}
  register: secret_result

- name: Load nginx config content
  ansible.builtin.set_fact:
    nginx_config_content: "{{ lookup('ansible.builtin.template', 'configs/nginx.conf.j2') }}"

- name: Create nginx config ConfigMap
  ansible.builtin.copy:
    content: "{{ configmap_content | to_nice_yaml(indent=2) }}"
    dest: "{{ tas_single_node_nginx_config }}"
    mode: "0600"
  vars:
    configmap_content:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: nginx-config
        namespace: nginx-system
      data:
        nginx.conf: "{{ nginx_config_content }}"

- name: Deploy nginx Pod
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      network: "{{ tas_single_node_podman_network }}"
      systemd_file: nginx
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/nginx/nginx.yaml') | from_yaml }}"
      configmap: "{{ tas_single_node_nginx_config }}"
      secret: "{{ tas_single_node_nginx_certs_config }}"
      secret_changed: "{{ secret_result.changed }}"
