---
- name: Confirmed required parameters provided
  ansible.builtin.assert:
    that:
      - tas_single_node_base_hostname is defined
      - tas_single_node_base_hostname | trim | length > 0
    msg: "'tas_single_node_base_hostname' must be specified"

- name: Slurp TSA Certificates chain
  ansible.builtin.slurp:
    src: "{{ item }}"
  loop:
    - "{{ tas_single_node_remote_tsa_private_key }}"
    - "{{ tas_single_node_remote_tsa_certificate_chain }}"
    - "{{ tas_single_node_remote_tsa_signer_private_key }}"
  register: remote_tsa_certificates

- name: Define TSA base secret data
  ansible.builtin.set_fact:
    secret_data:
      private_key.pem: |
        {{ (remote_tsa_certificates.results | selectattr('source', 'equalto', tas_single_node_remote_tsa_signer_private_key) | list | first).content }}
      certificate-chain.pem: |
        {{ (remote_tsa_certificates.results | selectattr('source', 'equalto', tas_single_node_remote_tsa_certificate_chain) | list | first).content }}
      password: "{{ tas_single_node_tsa_signer_passphrase | b64encode }}"

- name: Append Tink secret data
  ansible.builtin.set_fact:
    secret_data: "{{ secret_data | combine({'encrypted_key_set': tas_single_node_tsa_tink_keyset | b64encode}) }}"
  when: tas_single_node_tsa_signer_type == 'tink'

- name: Create TSA Secret
  ansible.builtin.copy:
    content: "{{ secret_content | to_nice_yaml(indent=2) }}"
    dest: "{{ tas_single_node_tsa_secret }}"
    mode: "0600"
  vars:
    secret_content:
      kind: Secret
      apiVersion: v1
      metadata:
        name: tsa-server-secret
        namespace: tsa-system
      data: "{{ secret_data }}"
  register: tsa_secret_result

- name: Deploy TSA Pod
  ansible.builtin.include_tasks: podman/install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: tsa
      network: "{{ tas_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/tsa/tsa-server.j2') | from_yaml }}"
      secret: "{{ tas_single_node_tsa_secret }}"
      secret_changed: "{{ tsa_secret_result.changed }}"
