- name: Verify
  hosts: molecule
  gather_facts: true
  become: true
  vars:
    test_dir_path: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../test"
  vars_files:
    - vars/vars.yml
    - "{{ molecule_ephemeral_directory }}/images.yml"
  tasks:
    - name: Load development build vars
      include_vars:
        file: "../../roles/tas_single_node/defaults/main.yml"
        name: dev_vars

    - name: Get pod information for multiple pods
      containers.podman.podman_pod_info:
        name: "{{ item.name }}"
      register: pod_info_list
      loop: "{{ tas_pods }}"

    - name: Get container information for all containers in the pods
      containers.podman.podman_container_info:
        name: "{{ container_ids }}"
      vars:
        container_ids: "{{ item.pods[0].Containers | map(attribute='Id') | list }}"
      loop: "{{ pod_info_list.results }}"
      loop_control:
        label: "{{ item.pods[0].Name }}"
      when: item.pods is defined and item.pods[0].Containers is defined
      register: container_info_list


    - name: Create a dictionary of pod names and container images
      set_fact:
        pod_images: "{{ pod_images | default({}) | combine({ pod_info_list.results[index].pods[0].Name: item.containers | map(attribute='ImageDigest') | list }) }}"
      loop: "{{ container_info_list.results }}"
      loop_control:
        index_var: index
    - name: Verify image digests
      assert:
        that:
          - digest in pod_images[item.name]
          - digest not in released_images[item.name]
      vars:
        digest: "{{ dev_vars[item.image_var].split('@')[1] }}"
      loop: "{{ tas_pods }}"
      loop_control:
        loop_var: item

    - name: Include create common tasks
      ansible.builtin.include_tasks:
        file: ../common/verify_common.yml
      vars:
        expected_validations: 2
