---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Load instance configs
      ansible.builtin.set_fact:
        instance_configs: "{{ (lookup('file', molecule_instance_config, errors='ignore') or '{}') | from_yaml }}"

    - name: print
      debug:
        msg: "{{ instance_configs }}"

    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        state: absent
        instance_ids:
          - "{{ item['instance'] }}"
        region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
      register: terminate_result
      with_items: "{{ instance_configs }}"
      changed_when: true
      failed_when: false

    - name: Dump instance configs
      ansible.builtin.copy:
        content: "{{ {} | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
        mode: "0600"

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        state: absent
