---
- name: Converge
  hosts: molecule
  gather_facts: true
  vars_files:
    - vars/vars.yml
    - vars/podman.yml
  tasks:
    - name: Error out if registry username is not set
      ansible.builtin.fail:
        msg: "Username for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_USERNAME env variable"
      when: tas_single_node_registry_username == ""

    - name: Error out if registry password is not set
      ansible.builtin.fail:
        msg: "Password for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_PASSWORD env variable"
      when: tas_single_node_registry_password == ""

    - name: Copy CA certificate content into tas_single_node_trillian_trusted_ca
      ansible.builtin.slurp:
        src: "/etc/mysql/ssl/ca-cert.pem"
      register: tas_single_node_trillian_trusted_ca

    - name: Debug CA certificate content from the remote
      ansible.builtin.debug:
        msg: "CA Certificate: {{ tas_single_node_trillian_trusted_ca.content | b64decode }}"

    # - name: Setting tas_single_node_trillian_trusted_ca
    #   ansible.builtin.debug:
    #     tas_single_node_trillian_trusted_ca: "{{ lookup('ansible.builtin.file', playbook_dir + '/ca-cert.pem') }}"

    - name: Apply tas_single_node role
      ansible.builtin.include_role:
        name: tas_single_node
