---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: default
platforms:
  - name: instance
    compose: CentOS-Stream-9
    arch: x86_64
    duration: 60
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
