---
- name: Prepare
  hosts: molecule
  gather_facts: true
  become: yes
  vars:
    users:
      - user: testingUser
        password: password123
  vars_files:
    - vars/vars.yml
  tasks:

    - name: Configure Dex OIDC instance
      ansible.builtin.include_tasks: ../common/dex-setup.yaml

    - name: Install Redis and MariaDB
      ansible.builtin.yum:
        name: 
          - redis
          - mariadb
          - mariadb-server
        state: latest

    - name: Set Redis password
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^# requirepass'
        line: 'requirepass password'

    - name: Allow external connections for Redis
      ansible.builtin.lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'bind 127.0.0.1 -::1'
        line: "#bind 127.0.0.1 -::1"

    - name: Enable and start Redis
      ansible.builtin.service:
        name: redis
        enabled: yes
        state: started

    - name: Allow external connections for MariaDB
      ansible.builtin.lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        regexp: '#bind_address=0.0.0.0'
        line: "bind_address=0.0.0.0"

    - name: Enable and start MariaDB
      ansible.builtin.service:
        name: mariadb
        enabled: yes
        state: started

    - name: Create Trillian Database
      shell: echo "CREATE DATABASE trillian;" | mysql

    - name: Download Trillian schema
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/securesign/trillian/refs/heads/main/storage/mysql/schema/storage.sql
        dest: /tmp/schema.sql
      retries: 5
      delay: 5

    - name: Import Trillian schema
      ansible.builtin.shell: |
        mysql -u root trillian < /tmp/schema.sql
 
    - name: Prepare MariaDB configuration
      ansible.builtin.shell: |
        mysql <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpassword';
        GRANT ALL ON *.* to 'root'@'%' IDENTIFIED BY 'rootpassword' WITH GRANT OPTION;
        DELETE FROM mysql.user WHERE User='';
        DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
        CREATE USER mysql;
        ALTER USER 'mysql'@'localhost' IDENTIFIED BY 'password';
        GRANT ALL ON trillian.* to 'mysql'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        EOF

        #- name: Set up a non-root sudoer to replicate a user environment
        #ansible.builtin.include_tasks: ../testing_user_setup.yaml
        #with_items: "{{ users }}" 

    - name: Generate TLS certificates for MariaDB
      ansible.builtin.shell: |
        rm -rf /etc/mysql/ssl
        mkdir -p /etc/mysql/ssl
        openssl genrsa -out /etc/mysql/ssl/ca-key.pem 2048
        openssl req -x509 -new -nodes -key /etc/mysql/ssl/ca-key.pem -sha256 -days 3650 -out /etc/mysql/ssl/ca-cert.pem -subj "/CN=CustomCA" \
          -addext "subjectAltName=DNS:localhost,IP:{{ ansible_default_ipv4.address }}"
        openssl genrsa -out /etc/mysql/ssl/server-key.pem 2048
        openssl req -new -key /etc/mysql/ssl/server-key.pem -out /etc/mysql/ssl/server-req.pem -subj "/CN=MySQLServer" \
            -addext "subjectAltName=DNS:localhost,IP:{{ ansible_default_ipv4.address }}"
        openssl x509 -req -in /etc/mysql/ssl/server-req.pem -CA /etc/mysql/ssl/ca-cert.pem -CAkey /etc/mysql/ssl/ca-key.pem -CAcreateserial \
            -out /etc/mysql/ssl/server-cert.pem -days 365 -sha256 -extfile <(printf "subjectAltName=DNS:localhost,IP:{{ ansible_default_ipv4.address }}")

        chmod 600 /etc/mysql/ssl/*.pem
        chown mysql:mysql /etc/mysql/ssl/*.pem
      args:
        creates: /etc/mysql/ssl/server-cert.pem

    - name: Configure TLS for MariaDB
      ansible.builtin.blockinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        block: |
          [mysqld]
          skip-name-resolve
          max_allowed_packet=64M
          max_connections=200
          wait_timeout=600
          interactive_timeout=600
          ssl-ca=/etc/mysql/ssl/ca-cert.pem
          ssl-cert=/etc/mysql/ssl/server-cert.pem
          ssl-key=/etc/mysql/ssl/server-key.pem
      notify:
        - Restart MariaDB

  handlers:
    - name: Restart MariaDB
      ansible.builtin.service:
        name: mariadb
        state: restarted
