---
- name: Converge
  hosts: molecule
  gather_facts: true
  vars_files:
    - vars/vars.yml
    - vars/podman.yml
  tasks:
    - name: Ensure Registry credentials are set
      ansible.builtin.include_tasks: ../check_creds.yml

    - name: Apply tas_single_node role
      ansible.builtin.include_role:
        name: tas_single_node
