---
- name: Converge
  hosts: molecule
  gather_facts: true
  vars_files:
    - vars/vars.yml
    - vars/podman.yml
  tasks:
    - name: Error out if registry username is not set
      ansible.builtin.fail:
        msg: "Username for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_USERNAME env variable"
      when: tas_single_node_registry_username == ""

    - name: Error out if registry password is not set
      ansible.builtin.fail:
        msg: "Password for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_PASSWORD env variable"
      when: tas_single_node_registry_password == ""

    - name: Verify CA certificate creation
      ansible.builtin.stat:
        path: /etc/mysql/ssl/ca-cert.pem
      register: ca_cert_stat

    - name: Prints CA certificate
      ansible.builtin.debug:
        msg:
        - "{{ ca_cert_stat }}"

    - name: Setting tas_single_node_trillian_trusted_ca
      become: yes
      ansible.builtin.set_fact:
        tas_single_node_trillian_trusted_ca: "{{ lookup('ansible.builtin.file', '/etc/mysql/ssl/ca-cert.pem') }}"

    - name: Apply tas_single_node role
      ansible.builtin.include_role:
        name: tas_single_node
