---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Check if instance ID file exists
      ansible.builtin.stat:
        path: "/tmp/instanceID.json"
      register: instanceStat

    - name: Terminate EC2 Instance
      block:
        - name: Load the instance ID from file
          ansible.builtin.slurp:
            src: "/tmp/instanceID.json"
          register: instanceFile

        - name: Set the fact from the file
          ansible.builtin.set_fact:
            instanceID: "{{ instanceFile.content | b64decode | from_json }}"
          when: instanceStat.stat.exists

        - name: Terminate EC2 instance
          amazon.aws.ec2_instance:
            state: absent
            instance_ids:
              - "{{ instanceID }}"
            region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          register: terminate_result

        - name: Print terminate result
          ansible.builtin.debug:
            var: terminate_result
      when: instanceStat.stat.exists

- name: Remove dynamic molecule inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove dynamic inventory file
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        state: absent
