---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
    compose: CentOS-Stream-9
    arch: x86_64
    duration: 45
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
