---
- name: Prepare
  hosts: molecule
  gather_facts: false
  become: yes
  vars:
    users:
      - user: testingUser
        password: password123
  vars_files:
    - vars/vars.yml

  tasks:

    - name: Install dnf versionlock plugin
      ansible.builtin.package:
        name: "python3-dnf-plugin-versionlock"
        state: latest

    # Ensure we test with the base RHEL 9.4 podman version.
    # We're ok with doing this only in the default scenario - if we get later
    # version in other scenarios, we actually get better test coverage for
    # different podman versions.
    - name: Lock podman to version 4.9
      ansible.builtin.command:
        cmd: "dnf versionlock add 'podman-4:4.9.4-16.el9_4.x86_64'"

    - name: Configure Dex OIDC instance
      ansible.builtin.include_tasks: ../common/dex-setup.yaml

      #- name: Setup a non-root sudoer to replicate a user environment
      #ansible.builtin.include_tasks: ../testing_user_setup.yaml
      #with_items: "{{ users }}"
