---
# defaults file for tas_single_node
tas_single_node_registry_username: ""
tas_single_node_registry_password: ""

tas_single_node_podman_network: rhtas

tas_single_node_setup_host_dns: true
tas_single_node_base_hostname: ""

tas_single_node_skip_os_install: false

tas_single_node_trust_root:
  full_archive: ""

# When adding or altering names for our images, consult the mapping in https://github.com/securesign/structural-tests
# To avoid breaking our structural tests

tas_single_node_fulcio_server_image:
  "registry.redhat.io/rhtas/fulcio-rhel9@sha256:5e3bce5d59f0c75a8178ddedcd5c7e8ee07544b5bc9382f8933ccca2b24bb10c"
tas_single_node_trillian_log_server_image:
  "registry.redhat.io/rhtas/trillian-logserver-rhel9@sha256:d458626dcaf975890665047a5c863b9962d1cf7ba0bff788fe06f20e225f320e"
tas_single_node_trillian_log_signer_image:
  "registry.redhat.io/rhtas/trillian-logsigner-rhel9@sha256:3608259e62e587c9d515338d0e00f6f074abe60fcd93338d4b0ee00446e23e8c"
tas_single_node_rekor_server_image:
  "registry.redhat.io/rhtas/rekor-server-rhel9@sha256:c322460c7b47ec791e8a32ff5844b0414df7b2c172fcaeebe47730dd3e99e44a"
tas_single_node_rekor_monitor_image:
  "registry.redhat.io/rhtas/rekor-monitor-rhel9@sha256:66356930e442450d05333c799185ca6f241838f57bfe98000a79475614070e72"
tas_single_node_ctlog_image:
  "registry.redhat.io/rhtas/certificate-transparency-rhel9@sha256:48d79f34792d52f4f92f99327c726baf23ffd69a84335680ab44f159960ab764"
tas_single_node_ctlog_monitor_image:
  "registry.redhat.io/rhtas/ctlog-monitor-rhel9@sha256:085ae861d8c3eead4ac3882f69fd65e7c38fdff1731b3bd17ca7e8e89e7d602a"
tas_single_node_rekor_redis_image:
  "registry.redhat.io/rhtas/trillian-redis-rhel9@sha256:3655b8bdb0de7c348c0fd6bfaa1c75bea535aa8c9ee30413d9f897a0f5385dbe"
tas_single_node_backfill_redis_image:
  "registry.redhat.io/rhtas/rekor-backfill-redis-rhel9@sha256:8be71af65d0ba1b85901e7b8b156f9255e825cd05ea1428439a1f47723f044cd"
tas_single_node_trillian_db_image:
  "registry.redhat.io/rhtas/trillian-database-rhel9@sha256:293274d23cdb63c76bcb7e6b6f70e79a1f96b3f93621fe959dcc63bdafb53fd5"
tas_single_node_tuf_image:
  "registry.redhat.io/rhtas/tuffer-rhel9@sha256:c39db5d599011cc925daa90c5dc24857f2b69a06f98bc9848e3a4516894f3521"
tas_single_node_http_server_image:
  "registry.redhat.io/ubi9/httpd-24@sha256:cd8e4f2bb54f535f68e48969d03b58581c7c2b47ee17c3e8b7893323a32bee3b"
tas_single_node_trillian_netcat_image:
  "registry.redhat.io/openshift4/ose-tools-rhel9@sha256:7c9d49fbb1c4b1bd2d3ea674fab638a68f361bafdc38a0ec3497333b53e42946"
tas_single_node_nginx_image:
  "registry.redhat.io/rhel9/nginx-124@sha256:da54bbccb61ef4c1229b501276e6af35878455471598426346bb3014571843ed"
tas_single_node_timestamp_authority_image:
  "registry.redhat.io/rhtas/timestamp-authority-rhel9@sha256:26b9b9c1534af8231baedc1e19abd5f7fcb1ba5608700461d9edb173ad5e8713"
tas_single_node_rekor_search_ui_image:
  "registry.redhat.io/rhtas/rekor-search-ui-rhel9@sha256:1b3c17dafcecb373afc6bf385da4a8547f0ed5a6488b383d8487fa5e0e639ca5"
# Create Tree
tas_single_node_createtree_image:
  "registry.redhat.io/rhtas/createtree-rhel9@sha256:f233fb3a6425a395d7cfe28658d9e0098915052b26d50e188e4b9d7cbbd8f458"
# CLI Server
tas_single_node_client_server_image:
  "registry.redhat.io/rhtas/client-server-rhel9@sha256:8263fafc2515affae84070f465065135cb4301ce8c02e2c8399c1caf1948f3b6"

tas_single_node_signing_config_url_mode: external

tas_single_node_podman: {}

# Volumes create options
tas_single_node_podman_volume_create_extra_args: {}

# Set to false to disable file logging.
tas_single_node_failure_log_enabled: true
tas_single_node_failure_log_dir: "{{ (tas_single_node_config_dir | default('/etc/rhtas')) }}/logs"
tas_single_node_failure_log_file: "{{ (tas_single_node_failure_log_dir | default('/etc/rhtas/logs')) }}/failures.log"
