---
# defaults file for tas_single_node
tas_single_node_registry_username: ""
tas_single_node_registry_password: ""

tas_single_node_podman_network: rhtas

tas_single_node_setup_host_dns: true
tas_single_node_base_hostname: ""

tas_single_node_skip_os_install: false

tas_single_node_trust_root:
  full_archive: ""

# When adding or altering names for our images, consult the mapping in https://github.com/securesign/structural-tests
# To avoid breaking our structural tests

tas_single_node_fulcio_server_image:
  "registry.redhat.io/rhtas/fulcio-rhel9@sha256:c9289244939c0fd2737e8768ac089d09d15ca42ea34e2512c13a73c159338ab7"
tas_single_node_trillian_log_server_image:
  "registry.redhat.io/rhtas/trillian-logserver-rhel9@sha256:b246d096ad6d2b19decfa3d87bca9ab2b78000aee28b717c0a33d1202a1b2d6b"
tas_single_node_trillian_log_signer_image:
  "registry.redhat.io/rhtas/trillian-logsigner-rhel9@sha256:d0f8b68e55173b010fd381e374f232a40fba6d03282cfd870bd9c12c492e4aec"
tas_single_node_rekor_server_image:
  "registry.redhat.io/rhtas/rekor-server-rhel9@sha256:4afca53f27929243177a80a08e1ca77bd8978a50e8e0e7929781bb7b14a85cd2"
tas_single_node_ctlog_image:
  "registry.redhat.io/rhtas/certificate-transparency-rhel9@sha256:7e70be684d2bc550f1d31b89eadcac24e6385b3578ad29d8bdaa17b260f9dbce"
tas_single_node_rekor_redis_image:
  "registry.redhat.io/rhtas/trillian-redis-rhel9@sha256:d97e6688aabf25ed1da6a8bf2012efb1772beed49b91456288418f6023a38dac"
tas_single_node_backfill_redis_image:
  "registry.redhat.io/rhtas/rekor-backfill-redis-rhel9@sha256:9b91bac976cf7c30b15f9a022996142e48711110ecd1c52663504e53dcfdcf09"
tas_single_node_trillian_db_image:
  "registry.redhat.io/rhtas/trillian-database-rhel9@sha256:50bc20bb57e8ee31e56637cafccfed2658982d81ca9bf1e71db9de4b82a2be36"
tas_single_node_tuf_image:
  "registry.redhat.io/rhtas/tuffer-rhel9@sha256:743bbe6b3a666225eb8ac30f667d20f3daeb0586a6c2d7005d3096c0e823dac5"
tas_single_node_http_server_image:
  "registry.redhat.io/ubi9/httpd-24@sha256:e7cfc9237b44ba31d78d520f1cdc1ff076bc1e1ad538bda3039cb772905e37f9"
tas_single_node_trillian_netcat_image:
  "registry.redhat.io/openshift4/ose-tools-rhel9@sha256:12f84700a69f6ce62efca960c2e4b6e3566b7065c97b9bb30376de37a0ca829f"
tas_single_node_nginx_image:
  "registry.redhat.io/rhel9/nginx-124@sha256:f3e0afbc6e1459a63b87ded4666b6ea3fa59a5d146d6bfa39995af936b1fb9f3"
tas_single_node_timestamp_authority_image:
  "registry.redhat.io/rhtas/timestamp-authority-rhel9@sha256:576d4fc358fffe5bedb93eb3fec68b9c040b1d50e6c4c56a3f8d49084c169e4f"
tas_single_node_rekor_search_ui_image:
  "registry.redhat.io/rhtas/rekor-search-ui-rhel9@sha256:1e3a46ade52215e2c78df9229f36301c94099e8397ee74ab99fb8bd504ce7aa2"
# Create Tree
tas_single_node_createtree_image:
  "registry.redhat.io/rhtas/createtree-rhel9@sha256:7a1e465f93e0560194b7d5d27b46453a0dd4ebb4072235da1ffbe4ccff91d452"
# CLI Server
tas_single_node_client_server_image:
  "registry.redhat.io/rhtas/client-server-rhel9@sha256:47071a0613d6d262110af4ce6703ce99db72c7ab58e3a6051b82f3098b372a49"

tas_single_node_podman: {}

# Volumes create options
tas_single_node_podman_volume_create_extra_args: {}
