---
# defaults file for tas_single_node
tas_single_node_registry_username: ""
tas_single_node_registry_password: ""

tas_single_node_podman_network: rhtas

tas_single_node_setup_host_dns: true
tas_single_node_base_hostname: ""

tas_single_node_skip_os_install: false

tas_single_node_trust_root:
  full_archive: ""

# When adding or altering names for our images, consult the mapping in https://github.com/securesign/structural-tests
# To avoid breaking our structural tests

tas_single_node_fulcio_server_image:
  "registry.redhat.io/rhtas/fulcio-rhel9@sha256:91ea31b9b1bb3d3dab0c381a0031e202c8f06486e658c0ff3b7259708f9c8491"
tas_single_node_trillian_log_server_image:
  "registry.redhat.io/rhtas/trillian-logserver-rhel9@sha256:4bc2abeef5bd8c16157a33577468201ebc6f8c81fb1b9cf65c028f464f24eb36"
tas_single_node_trillian_log_signer_image:
  "registry.redhat.io/rhtas/trillian-logsigner-rhel9@sha256:e1666e67b57dd4d46c74c275c524beca9c0303b6217ea97e8bb7f1753a569cf3"
tas_single_node_rekor_server_image:
  "registry.redhat.io/rhtas/rekor-server-rhel9@sha256:2303675b7d1d42f12c49b2017f7976f63d6f52d8d232c042a7339d84782e9690"
tas_single_node_rekor_monitor_image:
  "registry.redhat.io/rhtas/rekor-monitor-rhel9@sha256:b7f9f8b24fe7db4e124f9e5e9289bc2d180a810e253f48feb7e1177bbef6d4d0"
tas_single_node_ctlog_image:
  "registry.redhat.io/rhtas/certificate-transparency-rhel9@sha256:9ee667651970432bbcd2c4ce22f0cf557743707a0541ae054bec4bda5a7a9385"
tas_single_node_rekor_redis_image:
  "registry.redhat.io/rhtas/trillian-redis-rhel9@sha256:a966a9a274f3a9e2036ccb8a136279c48b2dd4f57d8c91b555ee9b77c645cb5d"
tas_single_node_backfill_redis_image:
  "registry.redhat.io/rhtas/rekor-backfill-redis-rhel9@sha256:6c4c76f786fdead6716a5315c05f50a3946085a7282fc2a6beafd8e163c2553b"
tas_single_node_trillian_db_image:
  "registry.redhat.io/rhtas/trillian-database-rhel9@sha256:68951d3664c544458405f58c3c1ac3898e3e41fcaeae095857bc1666c7d60d6c"
tas_single_node_tuf_image:
  "registry.redhat.io/rhtas/tuffer-rhel9@sha256:bb13d30ef76ed5d61d64978b27195ed6fb9b4916c932779411430e1dc63e2d46"
tas_single_node_http_server_image:
  "registry.redhat.io/ubi9/httpd-24@sha256:86a1a8b0d12c31c007dd411f7076a0cab2cc952ab8a0de74666fa09900c9fb86"
tas_single_node_trillian_netcat_image:
  "registry.redhat.io/openshift4/ose-tools-rhel9@sha256:6feb54137d60e5093e3e539bebfbe869831c38fb3376ccbc84357ed9aab76b75"
tas_single_node_nginx_image:
  "registry.redhat.io/rhel9/nginx-124@sha256:aa73fdb10af2bf24611ba714a412c2e65cec88a00eee628a0f2a75e564ec18f2"
tas_single_node_timestamp_authority_image:
  "registry.redhat.io/rhtas/timestamp-authority-rhel9@sha256:94e5b49ae8f3005483bd512036d2a78c7d8fccf6c5205bf79e9ae75fc12f69a3"
tas_single_node_rekor_search_ui_image:
  "registry.redhat.io/rhtas/rekor-search-ui-rhel9@sha256:2d5b39c47bf3b68e9d9d1b99341a88914d2aa9076ff928109bdbff88a982e25a"
# Create Tree
tas_single_node_createtree_image:
  "registry.redhat.io/rhtas/createtree-rhel9@sha256:70044a6cfc4f86e38ecbc7a4ffbfd713ccbd70fe0c99cac936ebaf1cb471ef87"
# CLI Server
tas_single_node_client_server_image:
  "registry.redhat.io/rhtas/client-server-rhel9@sha256:c81aaa8f300021d7cdbb964524fc5e89ea2c79fdab5507f0ec036bf96b219332"

tas_single_node_podman: {}

# Volumes create options
tas_single_node_podman_volume_create_extra_args: {}
