---
- name: Converge
  hosts: molecule
  gather_facts: true
  vars_files:
    - vars/vars.yml
    - vars/podman.yml
  tasks:
    - name: Ensure Registry credentials are set
      ansible.builtin.include_tasks: ../common/check_creds.yml

    - name: Copy CA certificate content into tas_single_node_trillian_trusted_ca
      ansible.builtin.slurp:
        src: "/etc/postgres/ssl/ca-cert.pem"
      register: ca_cert_content

    - name: Apply tas_single_node role
      ansible.builtin.include_role:
        name: tas_single_node
