---
- name: Converge
  hosts: molecule
  gather_facts: true
  vars_files:
    - vars/vars.yml
    # - vars/aap_nodes.yml
  tasks:
    # - name: Include aap variables
    #   ansible.builtin.include_vars:
    #     file: vars/aap_nodes.yml

    - name: Error out if registry username is not set
      ansible.builtin.fail:
        msg: "Username for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_USERNAME env variable"
      when: aap_setup_prep_inv_secrets.all.registry_username == ""

    - name: Error out if registry password is not set
      ansible.builtin.fail:
        msg: "Password for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_PASSWORD env variable"
      when: aap_setup_prep_inv_secrets.all.registry_password == ""

    - name: Include and execute AAP utility roles for setup
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - infra.aap_utilities.aap_setup_download
        - infra.aap_utilities.aap_setup_prepare

    - name: Install AAP
      ansible.builtin.shell:
        cmd: |
          cat /var/tmp/ansible-automation-platform-containerized-setup-2.5-*/inventory
          cd /var/tmp/ansible-automation-platform-containerized-setup-2.5-7
          ansible-playbook -i inventory ansible.containerized_installer.install
      changed_when: false
