---
- name: Converge
  hosts: molecule
  gather_facts: true
  tags: aap_installation
  vars_files:
    - vars/vars.yml
    - vars/aap_nodes.yml
  tasks:
    - name: Error out if registry username is not set
      ansible.builtin.fail:
        msg: "Username for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_USERNAME env variable"
      when: aap_setup_prep_inv_secrets.all.registry_username == ""

    - name: Error out if registry password is not set
      ansible.builtin.fail:
        msg: "Password for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_PASSWORD env variable"
      when: aap_setup_prep_inv_secrets.all.registry_password == ""

    - name: Include and execute AAP utility roles for setup
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - infra.aap_utilities.aap_setup_download
        - infra.aap_utilities.aap_setup_prepare

    # - name: Ensure ec2-user user has access to the setup directory
    #   ansible.builtin.file:
    #     path: "/var/tmp/ansible-automation-platform-containerized-setup-2.5-7"
    #     owner: ec2-user
    #     group: ec2-user
    #     mode: '0755'
    #   become: true
    #   become_user: root
    #   changed_when: false

    # - name: Ensure ec2-user user has access to the inventory file
    #   ansible.builtin.file:
    #     path: "/var/tmp/ansible-automation-platform-containerized-setup-2.5-7/inventory"
    #     owner: ec2-user
    #     group: ec2-user
    #     mode: '0644'
    #   become: true
    #   become_user: root
    #   changed_when: false

    - name: Install AAP
      ansible.builtin.shell:
        cmd: |
          cd /var/tmp/ansible-automation-platform-containerized-setup-2.5-7
          ansible-playbook -i inventory ansible.containerized_installer.install
      async: 1800
      poll: 0
      register: aap_install_task
      changed_when: false

    - name: Wait for AAP installation to complete
      ansible.builtin.async_status:
        jid: "{{ aap_install_task.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 30
