tas_single_node_base_hostname: yourrhtas
tas_single_node_cockpit:
  enabled: false
tas_single_node_registry_username: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_USERNAME') }}"
tas_single_node_registry_password: "{{ lookup('env', 'TAS_SINGLE_NODE_REGISTRY_PASSWORD') }}"

tas_single_node_fulcio:
  trusted_ca: "{{ lookup('file', '../common/dex/tls.crt') }}"
  fulcio_config:
    oidc_issuers:
      - issuer: "https://dex-idp:5556/dex"
        url: "https://dex-idp:5556/dex"
        client_id: trusted-artifact-signer
        type: email
