FROM fedora:40

RUN dnf install -y openssl vim && dnf clean all
RUN \
  #LATEST_VERSION=$(curl https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d : -f2 | tr -d "v\", ") && \
  #curl -O -L "https://github.com/sigstore/cosign/releases/latest/download/cosign-${LATEST_VERSION}-1.x86_64.rpm" && \
  #sudo rpm -ivh cosign-${LATEST_VERSION}-1.x86_64.rpm
  curl -O -L "https://github.com/sigstore/cosign/releases/download/v2.2.4/cosign-2.2.4-1.x86_64.rpm" && \
  sudo rpm -ivh cosign-2.2.4-1.x86_64.rpm
