- name: Verify
  hosts: molecule
  gather_facts: true
  become: true
  vars:
    test_dir_path: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../test"
  vars_files:
    - vars/vars.yml
  tasks:
      - name: Read fulcio config on molecule
        ansible.builtin.slurp:
          src: "{{ item.system_path }}"
        register: fulcio_configs
        loop:
          - { msg: "fulcio.key", system_path: "/etc/rhtas/certs/fulcio.key" }
          - { msg: "fulcio.pem", system_path: "/etc/rhtas/certs/fulcio.pem" }
        loop_control:
          label: "{{ item.msg }}"

      - name: Assert that new fulcio key and certificate were taken by TAS
        ansible.builtin.assert:
          that:
            - item.test_content == item.fulcio_config['content'] | b64decode
          fail_msg: "{{ item.msg }} was not taken by TAS"
          success_msg: "{{ item.msg }} was taken by TAS"
        loop:
          - { msg: "fulcio.key", test_content: "{{ lookup('file', molecule_scenario_directory + '/test_creds/fulcio/new-fulcio.key') }}", fulcio_config: "{{ fulcio_configs.results[0] }}" }
          - { msg: "fulcio.pem", test_content: "{{ lookup('file', molecule_scenario_directory + '/test_creds/fulcio/new-fulcio.pem') }}", fulcio_config: "{{ fulcio_configs.results[1] }}" }
        loop_control:
          label: "{{ item.msg }}"

      - name: Vefify fulcio.key backup
        block:
        - name: Find files with pattern fulcio.key.*
          ansible.builtin.find:
            paths: "/etc/rhtas/certs"
            patterns: "fulcio.key.*"
          register: found_files

        - name: Verify that at least one backup file exists
          ansible.builtin.fail:
            msg: "No files matching 'fulcio.key.*' were found."
          when: found_files.matched == 0

      - name: Vefify fulcio.pem backup
        block:
          - name: Find files with pattern fulcio.pem.*
            ansible.builtin.find:
              paths: "/etc/rhtas/certs"
              patterns: "fulcio.pem.*"
            register: found_files

          - name: Verify that at least one backup file exists
            ansible.builtin.fail:
              msg: "No files matching 'fulcio.pem.*' were found."
            when: found_files.matched == 0

      - name: Include create common tasks
        ansible.builtin.include_tasks:
          file: ../common/verify_common.yml
        vars:
          expected_validations: 2
