FROM fedora:43

RUN dnf install -y openssl vim && dnf clean all

ARG TARGETARCH
RUN \
  LATEST_VERSION=$(curl https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d : -f2 | tr -d "v\", ") && \
  if [ "$TARGETARCH" = "arm64" ]; then \
    RPM_URL="https://github.com/sigstore/cosign/releases/latest/download/cosign-${LATEST_VERSION}-1.aarch64.rpm"; \
  else \
    RPM_URL="https://github.com/sigstore/cosign/releases/latest/download/cosign-${LATEST_VERSION}-1.x86_64.rpm"; \
  fi && \
  curl -O -L "$RPM_URL" && \
  rpm -ivh "$(basename "$RPM_URL")"