FROM registry.redhat.io/rhtas/cosign-rhel9:1.3.2-1770107819 as cosign-bin

FROM fedora:45
RUN dnf install -y openssl vim && dnf clean all

COPY --from=cosign-bin /usr/local/bin/cosign /usr/local/bin/cosign
