name: Run ansible-lint
on:
  push:
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run ansible-lint
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-testing.txt
            ansible-lint -v
  molecule:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-testing.txt
            ansible-galaxy install -r requirements.yml
        - name: Run molecule
          env:
            TAS_SINGLE_NODE_REGISTRY_USERNAME: ${{ secrets.TAS_SINGLE_NODE_REGISTRY_USERNAME }}
            TAS_SINGLE_NODE_REGISTRY_PASSWORD: ${{ secrets.TAS_SINGLE_NODE_REGISTRY_PASSWORD }}
            TESTING_FARM_API_TOKEN: ${{ secrets.TESTING_FARM_API_TOKEN }}
          run: |
            molecule converge --scenario-name default
        - name: Destroy molecule infrastructure
          if: always()
          run:
            molecule destroy
            