name: Test upgrade path from last release to the development version
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  upgrade:
    env:
      AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
      TAS_SINGLE_NODE_REGISTRY_USERNAME: ${{ secrets.TAS_SINGLE_NODE_REGISTRY_USERNAME }}
      TAS_SINGLE_NODE_REGISTRY_PASSWORD: ${{ secrets.TAS_SINGLE_NODE_REGISTRY_PASSWORD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: "eu-north-1"
      GITHUB_RUN_ID: ${{ github.run_id }}
      SCENARIO_NAME: 'upgrade'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Automation Hub login
        uses: ./.github/actions/ah-login
        with:
          token: ${{ secrets.AUTOMATION_HUB_TOKEN }}

      - name: Install TAS using molecule test
        uses: ./.github/actions/molecule-test
        with:
          scenario: ${{ env.SCENARIO_NAME }}

      - name: Destroy molecule infrastructure
        if: always()
        run: |
          source venv/bin/activate
          molecule destroy --scenario-name ${{ env.SCENARIO_NAME }}
